### ISSUE TITLE
make deepab North-AHO default

### ISSUE THREAD

**Issue by antonkulaga** [RosettaCommons/DeepAb#9]
I am having issues by opening deepab models with Rosetta when I put Clothia scheme. In the same time when I do renumbering for deepab North-AHO with http://dunbrack2.fccc.edu/PyIgClassify/ things go well. Maybe you should make North-AHO the default numbering?

**Comment by jeffreyruffolo** [comment]
Currently DeepAb uses the Abnum server for renumbering which doesn't support North-AHO as far as I can tell. We opted to use Abnum because it's easy to interface with without avoid adding additional dependencies to the project, but it is a bit limited in options.
If you do need to run lots of predictions, I would recommend something like [ANARCI](https://github.com/oxpig/ANARCI) for renumbering if you want an automated process.
